[build]
  # Build SSR for Netlify (Nitro preset automatically detected in Netlify CI)
  command = "pnpm run build && mkdir -p .netlify/publish/_nuxt/builds/meta && if [ -d .output/public ]; then cp -R .output/public/* .netlify/publish/; fi && for SRC in .nuxt/dist/client node_modules/.cache/nuxt/.nuxt/dist/client; do if [ -d \"$SRC/_nuxt\" ]; then cp -R $SRC/_nuxt/* .netlify/publish/_nuxt/; fi; if [ -d \"$SRC/_nuxt/builds/meta\" ]; then cp -R $SRC/_nuxt/builds/meta/* .netlify/publish/_nuxt/builds/meta/; fi; done"
  publish = ".netlify/publish"

  # Configure environment for the build. These are safe to commit.
  # We tell Netlify's secrets scanner to ignore Nuxt public runtime keys,
  # since they are intentionally exposed in client assets.
  [build.environment]
    SECRETS_SCAN_OMIT_KEYS = "NUXT_PUBLIC_API_BASE,NUXT_PUBLIC_APP_NAME,NUXT_PUBLIC_TIME_ZONE"


